# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER ejobsg

# 挂载目录
VOLUME /home/ejobsg
# 创建目录
RUN mkdir -p /home/ejobsg
# 指定路径
WORKDIR /home/ejobsg
# 复制jar文件到路径
COPY ./jar/ejobsg-auth.jar /home/ejobsg/ejobsg-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","ejobsg-auth.jar"]
