version : '3.8'
services:
  ejobsg-nginx:
    container_name: ejobsg-nginx
    build:
      context: ./nginx
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/timezone
      - ./nginx/html/ejobsg-ui/dist:/home/ejobsg-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx

networks:
  docker_net:
    driver: bridge
